### ISSUE TITLE
Linker problem

### ISSUE THREAD

**Issue by DValmar** [ezibyte/EziSocial-Plugin#1]
Seems like EziSocialLib.a is compiled with GNU C++ stdlib, but modern cocos2d-x is build on LLVM stdlib.

![untitled](https://f.cloud.github.com/assets/1777329/899676/fc80f266-fb49-11e2-9e4c-fed063ff3539.png)

**Comment by ezibyte** [comment]
@DValmar I think you are trying to compile with Cocos2d v 3.0 ?

**Comment by ezibyte** [comment]
You easily use current lib with C++ 11 by following steps:

Goto -> Targets -> Build Phases -> Link Binary with Libraries 
and add libstdc++.6.dylib 

This should work. Let me know so that bug can be closed.
