### ISSUE TITLE
No libEziSocialPlugin.jar in v2.3

### ISSUE THREAD

**Issue by j-jorge** [ezibyte/EziSocial-Plugin#10]
Hi,

Since the release of version 2.3, the file `libEziSocialPlugin.jar` required for using EziSocial on Android is not in the repository anymore. Thus I cannot build my app after the update.

Can you please restore it?

Best regards,

Julien

**Comment by ezibyte** [comment]
Done https://github.com/ezibyte/EziSocial-Plugin/commit/08a851651c4178cdf12ac6741bacb04c7673dc0f
