### ISSUE TITLE
Incompatibility with Soomla

### ISSUE THREAD

**Issue by RubenVot** [ezibyte/EziSocial-Plugin#3]
We were trying to use Ezi in our new game but we have found that EziSocial doesn't work if Soomla is also installed. So we will have to write our own ndk. 

Since Soomla is not an open source project we were unable to find the concrete problem but we found that once "EziSocialManager.initWithActivity()" was called the pop up of the Play Store will never be opened. It looks like there is any conflict in life cycle of the activity.

**Comment by ezibyte** [comment]
Someone on Cocos2dx forum was saying Soomla is open-source? Did try contacting Soomla team?

**Comment by RubenVot** [comment]
We wanted to solve it on our own, but since we can't access code we can't fix it. Would be nice if you can provide a work around or a fix, because Ezi is a really useful framework and the price is acceptable.

**Comment by ezibyte** [comment]
We have never worked with Soomla Plugin. So it is difficult to say if can fix this too. We will check with Plunge Interactive team. They are working with both Soomla and EziSocial plugin. They may have some solution.

**Comment by RubenVot** [comment]
Great! thanks!
