### ISSUE TITLE
Twitter application not found

### ISSUE THREAD

**Issue by jandujar** [ezibyte/EziSocial-Plugin#4]
Hello,

I'm trying to integrate EziSocial on my android application "Guess the
Character", and I'm getting this error on launch.

"Twitter application not found"

Could you help me find a solution?

Twitter is installed and working. This is the output of the log. I'm
using an android tablet x86 with android 4.2.2

01-17 17:06:38.144: D/RouteManager(1779): setStreamParameters:
identical Platform State, do not reconsider routing
01-17 17:06:38.144: D/cocos2d-x debug info(29618): JS:
datos{"mensaje":"Jugando a  \"¡Adivina el personaje!\" de
@JanduSoft","url":"http://www.jandusoft.com/gtc","image":"http://www.jandusoft.com/images/gtc/banner_627x155.jpg"}
01-17 17:06:38.144: D/cocos2d-x debug info(29618): JSAPI log: shareTwitter
01-17 17:06:38.144: D/EziSocialManager(29618): I am inside EziSocial
Tweet message... with in JAVA
01-17 17:06:38.144: D/EziSocialManager(29618): Twitter shareIntent =
Intent { act=android.intent.action.SEND }
01-17 17:06:38.144: D/EziSocialManager(29618): Twitter PackageManager
= android.app.ApplicationPackageManager@20ddd0a8
01-17 17:06:38.144: I/WAKELOCK_ACQUIRE(2113):
TIMESTAMP=355098298972654, TAG=AudioOut_2, TYPE=PARTIAL_WAKE_LOCK
       , COUNT=0, PID=1779, UID=1013
01-17 17:06:38.154: D/EziSocialManager(29618): List of available activities...
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.android.bluetooth.opp.BluetoothOppLauncherActivity
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.asus.davinci.SNS.ui.BroadcastActivity
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.google.android.apps.plus.phone.SignOnActivity
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.asus.supernote.ShareToMeActivity
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.google.android.googlequicksearchbox.SearchActivity
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.google.android.gm.ComposeActivityGmail
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.asus.wifidirect.WiFiDirectActivity
01-17 17:06:38.154: D/EziSocialManager(29618): Activity =
com.twitter.applib.composer.TextFirstComposerActivity
01-17 17:06:38.154: E/EziSocialManager(29618): Twitter application not found.

**Comment by ezibyte** [comment]
Fixed in commit
https://github.com/ezibyte/EziSocial-Plugin/commit/6dc246c3779e7825e8d2c5e023d2e481d4ffa26a
